In [5]:
""" https://adventofcode.com/2022/day/8
"""
import pandas as pd


class DayEight:

    def __init__(self, input_fname):
        with open(input_fname, 'r') as f:
            data = f.readlines()
        self.df0 = pd.DataFrame([map(int, list(i.strip())) for i in data])
        display(self.df0)

    def part1(self):
        """ how many trees are visible from outside the grid?
        """
        self.df1 = self.df0.copy()
        self.df1.loc[:, :] = 0
        # look left and right
        for row in self.df0.index:
            lt = -1
            for col in self.df0.columns:
                if lt < self.df0.loc[row, col]:
                    lt = self.df0.loc[row, col]
                    self.df1.loc[row, col] = 1
            rt = -1
            for col in self.df0.columns[::-1]:
                if rt < self.df0.loc[row, col]:
                    rt = self.df0.loc[row, col]
                    self.df1.loc[row, col] = 1
        # look up and down
        for col in self.df0.columns:
            ut = -1
            for row in self.df0.index:
                if ut < self.df0.loc[row, col]:
                    ut = self.df0.loc[row, col]
                    self.df1.loc[row, col] = 1
            dt = -1
            for row in self.df0.index[::-1]:
                if dt < self.df0.loc[row, col]:
                    dt = self.df0.loc[row, col]
                    self.df1.loc[row, col] = 1
        # display(self.df1)
        print(self.df1.sum().sum())

    def score(self, row, col):
        max_col = self.df0.columns[-1]
        max_row = self.df0.index[-1]
        # look left
        ls = 0
        if col > 0:
            v = self.df0.loc[row, 0:col].tolist()[::-1]
            for i in v[1:]:
                ls += 1
                if i >= v[0]:
                    break
        # look right
        rs = 0
        if col < max_col:
            v = self.df0.loc[row, col:].tolist()
            for i in v[1:]:
                rs += 1
                if i >= v[0]:
                    break
        # look up
        us = 0
        if row > 0:
            v = self.df0.loc[0:row, col].tolist()[::-1]
            for i in v[1:]:
                us += 1
                if i >= v[0]:
                    break
        # look down
        ds = 0
        if row < max_row:
            v = self.df0.loc[row:, col].tolist()
            for i in v[1:]:
                ds += 1
                if i >= v[0]:
                    break
        return ls * rs * us * ds

    def part2(self):
        """ What is the highest scenic score possible for any tree?
        """
        self.df2 = self.df0.copy()
        self.df2.loc[:, :] = 0
        for row in self.df0.index:
            for col in self.df0.columns:
                self.df2.loc[row, col] = self.score(row, col)
        print(self.df2)
        print(self.df2.max().max())


# day8 = DayEight("sample.txt")
day8 = DayEight("input.txt")
day8.part1()
day8.part2()

,0,1,2,3,4,5,6,7,8,9,...,89,90,91,92,93,94,95,96,97,98
0,2,3,0,3,0,2,1,0,2,3,...,2,1,1,2,1,0,0,2,2,1
1,3,2,2,2,0,0,1,2,0,1,...,3,1,0,2,1,1,1,0,3,2
2,2,2,0,3,0,0,2,0,1,0,...,2,1,2,0,3,0,3,3,2,0
3,1,3,1,3,0,1,0,3,4,1,...,4,4,3,0,0,1,2,2,3,1
4,0,2,1,0,0,0,4,3,1,3,...,0,0,1,2,2,0,2,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,0,2,2,1,0,1,1,3,1,2,...,3,2,2,1,4,3,2,0,3,2
95,2,3,3,2,3,3,0,0,1,1,...,0,2,0,3,3,3,1,3,3,3
96,2,2,1,2,3,4,2,0,0,4,...,1,4,2,2,0,4,2,1,0,3
97,3,2,1,1,2,3,4,0,1,1,...,2,4,2,3,4,1,0,2,2,3
98,1,2,2,3,3,3,2,4,4,1,...,4,2,3,3,3,3,3,2,0,3

1684
    0   1   2   3   4    5    6    7     8   9   ...   89   90  91  92   93  \
0    0   0   0   0   0    0    0    0     0   0  ...    0    0   0   0    0
1    0   1   5   4   1    1    3   24     1   4  ...   16    2   1  45    1
2    0   2   1  42   1    1   48    1     8   1  ...    8    1   8   1  128
3    0  12   2  32   1   24    1   12  1008   2  ...  126  120  36   1    1
4    0   5   8   1   1    1  840    2     1  48  ...    1    1   3  84    8
..  ..  ..  ..  ..  ..  ...  ...  ...   ...  ..  ...  ...  ...  ..  ..  ...
94   0   3   5   2   1    2    2  140     1  36  ...   32    3   4   1  225
95   0  12  12   2   4   21    1    1     6   1  ...    1    4   1  48    2
96   0   2   1   4   8  480    9    1     1  96  ...    2  128   2   2    1
97   0   3   1   1   3    5  360    1     4   1  ...    9   12   1   4   45
98   0   0   0   0   0    0    0    0     0   0  ...    0    0   0   0    0

     94  95  96  97  98
0     0   0   0   0   0
1     2   2   1  16   0
2     1  12  12   1   0
3    12   4   2  48   0
4     1   6   2   1   0
..  ...  ..  ..  ..  ..
94   27   8   1   6   0
95    2   1  12   3   0
96  352  12   2   1   0
97    2   1   6   2   0
98    0   0   0   0   0

[99 rows x 99 columns]
486540